/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import DAO.AgendaDAO;
import static DAO.AgendaDAO.getContato;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabif
 */
public class TCompromisso extends javax.swing.JFrame {

    private TInicial t1;
    private TContato t2;
    private TMain t4;
    private TGrupo t5;
    private TUsuario t6;
    private TCriarGrupo t7;
    
    DefaultTableModel modelContatos;
    
    public TCompromisso() {
        initComponents();
        
        modelContatos = (DefaultTableModel) TableT9Contatos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelT3Participantes = new javax.swing.JLabel();
        LabelT3DtFinal = new javax.swing.JLabel();
        TextT3Titulo = new javax.swing.JTextField();
        TextT3DtFinal = new javax.swing.JTextField();
        TextT3Dtinicial = new javax.swing.JTextField();
        TextT3Local = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaT3Descricao = new javax.swing.JTextArea();
        BtT3Voltar = new javax.swing.JButton();
        BtT3Salvar = new javax.swing.JButton();
        BtT3Editar = new javax.swing.JButton();
        LabelT3NovoCompromisso = new javax.swing.JLabel();
        LabelT3Titulo = new javax.swing.JLabel();
        LabelT3Descricao = new javax.swing.JLabel();
        LabelT3DtInicial = new javax.swing.JLabel();
        LabelT3Local = new javax.swing.JLabel();
        TexT3tIdComp = new javax.swing.JTextField();
        TextT3IdCont = new javax.swing.JTextField();
        LabelT3Participantes2 = new javax.swing.JLabel();
        LabelT3Participantes3 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableT9Contatos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelT3Participantes.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3Participantes.setText("Participantes");

        LabelT3DtFinal.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3DtFinal.setText("Data e hora final");

        TextT3DtFinal.setText("Formato dd/mm/aa hh:mm:ss");

        TextT3Dtinicial.setText("Formato dd/mm/aa hh:mm:ss");

        AreaT3Descricao.setColumns(20);
        AreaT3Descricao.setRows(5);
        jScrollPane1.setViewportView(AreaT3Descricao);

        BtT3Voltar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT3Voltar.setText("Voltar");
        BtT3Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT3VoltarActionPerformed(evt);
            }
        });

        BtT3Salvar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT3Salvar.setText("Salvar");
        BtT3Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT3SalvarActionPerformed(evt);
            }
        });

        BtT3Editar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT3Editar.setText("Adicionar participante");
        BtT3Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT3EditarActionPerformed(evt);
            }
        });

        LabelT3NovoCompromisso.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 36)); // NOI18N
        LabelT3NovoCompromisso.setText("Compromisso");

        LabelT3Titulo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3Titulo.setText("Título");

        LabelT3Descricao.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3Descricao.setText("Descricão");
        LabelT3Descricao.setToolTipText("");

        LabelT3DtInicial.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3DtInicial.setText("Data e hora inicial");

        LabelT3Local.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3Local.setText("Local");

        TexT3tIdComp.setEditable(false);
        TexT3tIdComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TexT3tIdCompActionPerformed(evt);
            }
        });

        LabelT3Participantes2.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3Participantes2.setText("Id do contato");

        LabelT3Participantes3.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT3Participantes3.setText("Id do compromisso");

        TableT9Contatos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        TableT9Contatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TableT9Contatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelT3NovoCompromisso)
                .addGap(357, 357, 357)
                .addComponent(BtT3Voltar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelT3Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT3Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT3DtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT3DtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT3Local, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextT3Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(LabelT3Participantes, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TextT3Local, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT3Dtinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT3DtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(97, 97, 97)
                                .addComponent(BtT3Salvar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(135, 135, 135)
                                        .addComponent(TexT3tIdComp, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(86, 86, 86)
                                        .addComponent(TextT3IdCont, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(162, 162, 162)
                                        .addComponent(BtT3Editar)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelT3Participantes3)
                                .addGap(18, 18, 18)
                                .addComponent(LabelT3Participantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(100, 100, 100))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(86, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtT3Voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LabelT3NovoCompromisso)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelT3Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(182, 182, 182)
                                .addComponent(LabelT3DtInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LabelT3DtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelT3Descricao, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(LabelT3Local, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextT3Titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelT3Participantes, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextT3Dtinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TextT3DtFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelT3Participantes2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LabelT3Participantes3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TextT3IdCont, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TexT3tIdComp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TextT3Local, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtT3Salvar)
                    .addComponent(BtT3Editar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtT3VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT3VoltarActionPerformed
        this.t4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtT3VoltarActionPerformed

    private void BtT3SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT3SalvarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy hh:mm:ss"); 
        java.sql.Timestamp data1 = null, data2 = null;
        
        try {
            data1 = new java.sql.Timestamp(formato.parse(this.TextT3Dtinicial.getText()).getTime());
            data2 = new java.sql.Timestamp(formato.parse(this.TextT3DtFinal.getText()).getTime());
        } catch (ParseException ex) {
            java.util.logging.Logger.getLogger(TCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
            
        
        AgendaDAO agendaDao = new AgendaDAO();
        Compromisso c = new Compromisso();

        //c.setId();
        c.setTitulo(this.TextT3Titulo.getText());
        c.setDescricao(this.AreaT3Descricao.getText());
        c.setHorainicio(data1);
        c.setHorafim(data2);
        c.setLocal(this.TextT3Local.getText());
        //c.setEmail(this.TextT2Email.getText());
        
        String a = this.TextT3Titulo.getText();
        String b = this.AreaT3Descricao.getText();

        AgendaDAO.SaveComp(c);
        
        this.TexT3tIdComp.setText(String.valueOf(AgendaDAO.GetIdComp(a, b)));
    }//GEN-LAST:event_BtT3SalvarActionPerformed

    private void TexT3tIdCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TexT3tIdCompActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TexT3tIdCompActionPerformed

    private void BtT3EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT3EditarActionPerformed
        AgendaDAO agendaDao = new AgendaDAO();
        AgendaDAO.AddPart((Integer.parseInt(this.TexT3tIdComp.getText())), (Integer.parseInt(this.TextT3IdCont.getText())));
    }//GEN-LAST:event_BtT3EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCompromisso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCompromisso().setVisible(true);
            }
        });
    }
    
    void AtualizarContatos(){
        AgendaDAO contatoDAO = new AgendaDAO();
        List<Contato> contatos = new ArrayList<Contato>();
        contatos  = getContato();
        
        modelContatos.setRowCount(0);
        
        for (int i = 0; i < contatos.size(); i++)
        {
            modelContatos.insertRow(modelContatos.getRowCount(), new Object[]{String.valueOf(contatos.get(i).getId()), String.valueOf(contatos.get(i).getNome()), String.valueOf(contatos.get(i).getTelefone())});
        }
    }
    
    void setTelas(TInicial t1, TContato t2, TMain t4, TGrupo t5, TUsuario t6,  TCriarGrupo t7) {
        this.t1 = t1;
        this.t2 = t2;
        this.t4 = t4;
        this.t5 = t5;
        this.t6 = t6;
        this.t7 = t7;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaT3Descricao;
    private javax.swing.JButton BtT3Editar;
    private javax.swing.JButton BtT3Salvar;
    private javax.swing.JButton BtT3Voltar;
    private javax.swing.JLabel LabelT3Descricao;
    private javax.swing.JLabel LabelT3DtFinal;
    private javax.swing.JLabel LabelT3DtInicial;
    private javax.swing.JLabel LabelT3Local;
    private javax.swing.JLabel LabelT3NovoCompromisso;
    private javax.swing.JLabel LabelT3Participantes;
    private javax.swing.JLabel LabelT3Participantes2;
    private javax.swing.JLabel LabelT3Participantes3;
    private javax.swing.JLabel LabelT3Titulo;
    private javax.swing.JTable TableT9Contatos;
    private javax.swing.JTextField TexT3tIdComp;
    private javax.swing.JTextField TextT3DtFinal;
    private javax.swing.JTextField TextT3Dtinicial;
    private javax.swing.JTextField TextT3IdCont;
    private javax.swing.JTextField TextT3Local;
    private javax.swing.JTextField TextT3Titulo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane6;
    // End of variables declaration//GEN-END:variables
}
