/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import DAO.AgendaDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author gabif
 */
public class TContato extends javax.swing.JFrame {

    private TInicial t1;
    private TCompromisso t3;
    private TMain t4;
    private TGrupo t5;
    private TUsuario t6;
    private TCriarGrupo t7;
    
    public TContato() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextT2Endereco = new javax.swing.JTextField();
        TextT2DtNasc = new javax.swing.JTextField();
        LabelT2Contato = new javax.swing.JLabel();
        BtT2Voltar = new javax.swing.JButton();
        LabelT2DtNasc = new javax.swing.JLabel();
        LabelT2Nome = new javax.swing.JLabel();
        LabelT2Telefone = new javax.swing.JLabel();
        BtT2Salvar = new javax.swing.JButton();
        LabelT2Endereco = new javax.swing.JLabel();
        LabelT2Email = new javax.swing.JLabel();
        TextT2Nome = new javax.swing.JTextField();
        TextT2Telefone = new javax.swing.JTextField();
        TextT2Email = new javax.swing.JTextField();
        BtT2Editar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelT2Contato.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 36)); // NOI18N
        LabelT2Contato.setText("Contato");

        BtT2Voltar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT2Voltar.setText("Voltar");
        BtT2Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT2VoltarActionPerformed(evt);
            }
        });

        LabelT2DtNasc.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2DtNasc.setText("Data de Nascimento");

        LabelT2Nome.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Nome.setText("Nome");

        LabelT2Telefone.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Telefone.setText("Telefone");

        BtT2Salvar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT2Salvar.setText("Salvar");
        BtT2Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT2SalvarActionPerformed(evt);
            }
        });

        LabelT2Endereco.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Endereco.setText("Endereco");

        LabelT2Email.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Email.setText("E-mail");

        TextT2Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextT2NomeActionPerformed(evt);
            }
        });

        BtT2Editar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT2Editar.setText("Editar");
        BtT2Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT2EditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelT2Contato)
                .addGap(383, 383, 383)
                .addComponent(BtT2Voltar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(300, 300, 300)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelT2DtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Email, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextT2Endereco)
                    .addComponent(TextT2Nome)
                    .addComponent(TextT2DtNasc)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtT2Editar)
                                .addGap(130, 130, 130)
                                .addComponent(BtT2Salvar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(TextT2Email, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(TextT2Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(278, 278, 278))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BtT2Voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(LabelT2Contato)))
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelT2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(LabelT2DtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(LabelT2Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(LabelT2Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(LabelT2Email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(TextT2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(TextT2DtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(TextT2Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(TextT2Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(TextT2Email)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtT2Editar)
                    .addComponent(BtT2Salvar))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextT2NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextT2NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextT2NomeActionPerformed

    private void BtT2SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT2SalvarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy"); 
        java.sql.Date data = null;
        try {
            data = new java.sql.Date(formato.parse(this.TextT2DtNasc.getText()).getTime());
        } catch (ParseException ex) {
            Logger.getLogger(TContato.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        AgendaDAO agendaDao = new AgendaDAO();
        Contato c = new Contato();
        
        //c.setId();
        c.setNome(this.TextT2Nome.getText());
        c.setNascimento(data);
        c.setEndereco(this.TextT2Endereco.getText());
        c.setTelefone(this.TextT2Telefone.getText());
        c.setEmail(this.TextT2Email.getText());
        
        AgendaDAO.Save(c);
    }//GEN-LAST:event_BtT2SalvarActionPerformed

    private void BtT2VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT2VoltarActionPerformed
        this.t4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtT2VoltarActionPerformed

    private void BtT2EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT2EditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtT2EditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TContato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TContato().setVisible(true);
            }
        });
    }
    
    void setTelas(TInicial t1, TCompromisso t3, TMain t4, TGrupo t5, TUsuario t6,  TCriarGrupo t7) {
        this.t1 = t1;
        this.t3 = t3;
        this.t4 = t4;
        this.t5 = t5;
        this.t6 = t6;
        this.t7 = t7;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtT2Editar;
    private javax.swing.JButton BtT2Salvar;
    private javax.swing.JButton BtT2Voltar;
    private javax.swing.JLabel LabelT2Contato;
    private javax.swing.JLabel LabelT2DtNasc;
    private javax.swing.JLabel LabelT2Email;
    private javax.swing.JLabel LabelT2Endereco;
    private javax.swing.JLabel LabelT2Nome;
    private javax.swing.JLabel LabelT2Telefone;
    private javax.swing.JTextField TextT2DtNasc;
    private javax.swing.JTextField TextT2Email;
    private javax.swing.JTextField TextT2Endereco;
    private javax.swing.JTextField TextT2Nome;
    private javax.swing.JTextField TextT2Telefone;
    // End of variables declaration//GEN-END:variables
}
