/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import DAO.GrupoDAO;
import static DAO.GrupoDAO.getGrupo;
import DAO.UsuarioDAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TCriarGrupo extends javax.swing.JFrame {

    private TInicial t1;
    private TContato t2;
    private TCompromisso t3;
    private TMain t4;
    private TGrupo t5;
    private TUsuario t6;
    
    DefaultTableModel model;    
    
    
    public TCriarGrupo() {
        initComponents();
        
        model = (DefaultTableModel) TabT6Grupos.getModel();
        Atualizar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextT7NomeGrupo = new javax.swing.JTextField();
        LabelT5Todos = new javax.swing.JLabel();
        LabelT5Nome = new javax.swing.JLabel();
        LabelT5NovoGrupo = new javax.swing.JLabel();
        BtT5Salvar = new javax.swing.JButton();
        BtT5Voltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabT6Grupos = new javax.swing.JTable();
        BtT7AddContatoGrupo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelT5Todos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT5Todos.setText("Grupos");

        LabelT5Nome.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT5Nome.setText("Nome");

        LabelT5NovoGrupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 36)); // NOI18N
        LabelT5NovoGrupo.setText("Criar Grupo");

        BtT5Salvar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT5Salvar.setText("Salvar");
        BtT5Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT5SalvarActionPerformed(evt);
            }
        });

        BtT5Voltar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT5Voltar.setText("Voltar");
        BtT5Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT5VoltarActionPerformed(evt);
            }
        });

        TabT6Grupos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        TabT6Grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabT6Grupos);

        BtT7AddContatoGrupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT7AddContatoGrupo.setText("Adicionar contato a um grupo");
        BtT7AddContatoGrupo.setActionCommand("");
        BtT7AddContatoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT7AddContatoGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelT5NovoGrupo)
                        .addGap(295, 295, 295)
                        .addComponent(BtT5Voltar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtT5Salvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(414, 414, 414)
                                .addComponent(LabelT5Todos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(LabelT5Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TextT7NomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(316, 316, 316)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(BtT7AddContatoGrupo))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 159, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(LabelT5NovoGrupo)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextT7NomeGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT5Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(LabelT5Todos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtT7AddContatoGrupo)
                .addContainerGap(140, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtT5Voltar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtT5Salvar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtT5SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT5SalvarActionPerformed

        GrupoDAO grupoDao = new GrupoDAO();
        Grupo g = new Grupo();
       
        //c.setId();
        g.setNome(this.TextT7NomeGrupo.getText());
        
        GrupoDAO.Save(g);
        Atualizar();
    }//GEN-LAST:event_BtT5SalvarActionPerformed

    private void BtT5VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT5VoltarActionPerformed
        this.t4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtT5VoltarActionPerformed

    private void BtT7AddContatoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT7AddContatoGrupoActionPerformed
        this.setVisible(false);
        this.t5.setVisible(true);
    }//GEN-LAST:event_BtT7AddContatoGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCriarGrupo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCriarGrupo().setVisible(true);
            }
        });
    }
    
    void setTelas(TInicial t1, TContato t2, TCompromisso t3, TMain t4, TGrupo t5, TUsuario t6) {
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
        this.t4 = t4;
        this.t5 = t5;
        this.t6 = t6;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtT5Salvar;
    private javax.swing.JButton BtT5Voltar;
    private javax.swing.JButton BtT7AddContatoGrupo;
    private javax.swing.JLabel LabelT5Nome;
    private javax.swing.JLabel LabelT5NovoGrupo;
    private javax.swing.JLabel LabelT5Todos;
    private javax.swing.JTable TabT6Grupos;
    private javax.swing.JTextField TextT7NomeGrupo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void Atualizar() {
        GrupoDAO grupoDAO = new GrupoDAO();
        List<Grupo> grupos = new ArrayList<Grupo>();
        grupos  = getGrupo();
        
        model.setRowCount(0);
        
        for (int i = 0; i < grupos.size(); i++)
        {
            model.insertRow(model.getRowCount(), new Object[]{String.valueOf(grupos.get(i).getId()), String.valueOf(grupos.get(i).getNome())});
        }
    }
}
