/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;
import DAO.UsuarioDAO;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
/**
 *
 * @author gabif
 */
public class TInicial extends javax.swing.JFrame {

    private TContato t2;
    private TCompromisso t3;
    private TMain t4;
    private TGrupo t5;
    private TUsuario t6;
    
    public TInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelT1Senha = new javax.swing.JLabel();
        LabelT1Login = new javax.swing.JLabel();
        TextT1Senha = new javax.swing.JPasswordField();
        CheckBoxT1Lembrar = new javax.swing.JCheckBox();
        LabelT1Agenda = new javax.swing.JLabel();
        TextT1Login = new javax.swing.JTextField();
        BtT1NovoUsuario = new javax.swing.JButton();
        BtT1Login = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelT1Senha.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT1Senha.setText("Senha");
        LabelT1Senha.setToolTipText("");

        LabelT1Login.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT1Login.setText("Id");

        CheckBoxT1Lembrar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        CheckBoxT1Lembrar.setText("Lembre-se de mim");
        CheckBoxT1Lembrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBoxT1LembrarActionPerformed(evt);
            }
        });

        LabelT1Agenda.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 52)); // NOI18N
        LabelT1Agenda.setText("Agenda de Contatos");

        BtT1NovoUsuario.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        BtT1NovoUsuario.setText("Novo Usuário");
        BtT1NovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT1NovoUsuarioActionPerformed(evt);
            }
        });

        BtT1Login.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        BtT1Login.setText("Log in");
        BtT1Login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT1LoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(345, 345, 345)
                                .addComponent(LabelT1Agenda))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(314, 314, 314)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LabelT1Login, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LabelT1Senha, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(CheckBoxT1Lembrar)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BtT1Login))
                                    .addComponent(TextT1Login)
                                    .addComponent(TextT1Senha, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE))))
                        .addGap(0, 337, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtT1NovoUsuario)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(LabelT1Agenda)
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(TextT1Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT1Login, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelT1Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextT1Senha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBoxT1Lembrar)
                    .addComponent(BtT1Login))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addComponent(BtT1NovoUsuario)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBoxT1LembrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBoxT1LembrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckBoxT1LembrarActionPerformed

    private void BtT1LoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT1LoginActionPerformed
        try{
            String nome_usuario, senha_usuario;
        
            String pwd = new String(TextT1Senha.getPassword());
            nome_usuario = TextT1Login.getText();
            senha_usuario = pwd;
        
            Usuario objusuario = new Usuario();
            objusuario.setNome(nome_usuario);
            objusuario.setSenha(senha_usuario);
            
            UsuarioDAO objusuariodao = new UsuarioDAO();
            ResultSet rsusuariodao = objusuariodao.autenticacaoUsuario(objusuario);
            
            if (rsusuariodao.next()){
                //Chamar tela a abrir
                this.t4.setVisible(true);
                dispose();
                //this.setVisible(false);
            } else {
                //msg dizendo incorreto
                JOptionPane.showMessageDialog(null, "Usuario ou senha invalida");
            }
            
        } catch (SQLException erro) {
            JOptionPane.showMessageDialog(null, "FRMLOGINVIEW" + erro);
        }
    }//GEN-LAST:event_BtT1LoginActionPerformed

    private void BtT1NovoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT1NovoUsuarioActionPerformed
        this.t6.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtT1NovoUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TInicial().setVisible(true);
            }
        });
    }
    
    void setTelas(TContato t2, TCompromisso t3, TMain t4, TGrupo t5, TUsuario t6) {
        this.t2 = t2;
        this.t3 = t3;
        this.t4 = t4;
        this.t5 = t5;
        this.t6 = t6;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtT1Login;
    private javax.swing.JButton BtT1NovoUsuario;
    private javax.swing.JCheckBox CheckBoxT1Lembrar;
    private javax.swing.JLabel LabelT1Agenda;
    private javax.swing.JLabel LabelT1Login;
    private javax.swing.JLabel LabelT1Senha;
    private javax.swing.JTextField TextT1Login;
    private javax.swing.JPasswordField TextT1Senha;
    // End of variables declaration//GEN-END:variables
}
