/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

/**
 *
 * @author gabif
 */
public class TMain extends javax.swing.JFrame {

    private TInicial t1;
    private TContato t2;
    private TCompromisso t3;
    private TGrupo t5;
    private TUsuario t6;
    private TParticipantes t7;
    
    public TMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelT4Grupos = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        AreaT4Grupos = new javax.swing.JTextArea();
        BtT4Grupo = new javax.swing.JButton();
        BtT4EditUser = new javax.swing.JButton();
        BtT4Contato = new javax.swing.JButton();
        LabelT4Compromissos = new javax.swing.JLabel();
        BtT4Compromissos = new javax.swing.JButton();
        LabelT4Contatos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        AreaT4Compromissos = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        AreaT4Contatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelT4Grupos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT4Grupos.setText("Grupos");

        AreaT4Grupos.setColumns(20);
        AreaT4Grupos.setRows(5);
        jScrollPane3.setViewportView(AreaT4Grupos);

        BtT4Grupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4Grupo.setText("Novo grupo");

        BtT4EditUser.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4EditUser.setText("Meu usuário");

        BtT4Contato.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4Contato.setText("Novo contato");

        LabelT4Compromissos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT4Compromissos.setText("Compromissos");

        BtT4Compromissos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4Compromissos.setText("Novo compromisso");
        BtT4Compromissos.setToolTipText("");

        LabelT4Contatos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT4Contatos.setText("Contatos");

        AreaT4Compromissos.setColumns(20);
        AreaT4Compromissos.setRows(5);
        jScrollPane1.setViewportView(AreaT4Compromissos);

        AreaT4Contatos.setColumns(20);
        AreaT4Contatos.setRows(5);
        jScrollPane2.setViewportView(AreaT4Contatos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtT4EditUser)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(LabelT4Contatos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelT4Grupos)
                        .addGap(254, 254, 254)
                        .addComponent(LabelT4Compromissos)
                        .addGap(80, 80, 80))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(BtT4Contato)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtT4Grupo)
                        .addGap(228, 228, 228)
                        .addComponent(BtT4Compromissos)
                        .addGap(56, 56, 56)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtT4EditUser)
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelT4Contatos)
                    .addComponent(LabelT4Compromissos)
                    .addComponent(LabelT4Grupos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtT4Grupo)
                    .addComponent(BtT4Compromissos)
                    .addComponent(BtT4Contato))
                .addContainerGap(144, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TMain().setVisible(true);
            }
        });
    }
    
    void setTelas(TInicial t1, TContato t2, TCompromisso t3, TGrupo t5, TUsuario t6, TParticipantes t7) {
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
        this.t5 = t5;
        this.t6 = t6;
        this.t7 = t7;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AreaT4Compromissos;
    private javax.swing.JTextArea AreaT4Contatos;
    private javax.swing.JTextArea AreaT4Grupos;
    private javax.swing.JButton BtT4Compromissos;
    private javax.swing.JButton BtT4Contato;
    private javax.swing.JButton BtT4EditUser;
    private javax.swing.JButton BtT4Grupo;
    private javax.swing.JLabel LabelT4Compromissos;
    private javax.swing.JLabel LabelT4Contatos;
    private javax.swing.JLabel LabelT4Grupos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
