/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import DAO.AgendaDAO;
import static DAO.AgendaDAO.getContato;
import DAO.GrupoDAO;
import static DAO.GrupoDAO.getGrupo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gabif
 */
public class TMain extends javax.swing.JFrame {

    private TInicial t1;
    private TContato t2;
    private TCompromisso t3;
    private TGrupo t5;
    private TUsuario t6;
    private TCriarGrupo t7;
    private TVisualizarGrupos t8;
    
    DefaultTableModel modelContatos;
    DefaultTableModel modelGrupos;
    
    public TMain() {
        initComponents();
        
        modelGrupos = (DefaultTableModel) TableT4Grupos.getModel();
        modelContatos = (DefaultTableModel) TableT4Contatos.getModel();
        AtualizarContatos();
        AtualizarGrupos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        LabelT4Grupos = new javax.swing.JLabel();
        BtT4AddContatoGrupo = new javax.swing.JButton();
        BtT4EditUser = new javax.swing.JButton();
        BtT4Contato = new javax.swing.JButton();
        LabelT4Compromissos = new javax.swing.JLabel();
        BtT4Compromissos = new javax.swing.JButton();
        LabelT4Contatos = new javax.swing.JLabel();
        LabelT6Nome = new javax.swing.JLabel();
        LabelT6Agenda = new javax.swing.JLabel();
        BtT4Atualizar = new javax.swing.JButton();
        BtT4NovoGrupo = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableT4Grupos = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        TableT4Contatos = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        TableT4Compromissos = new javax.swing.JTable();
        BtT4ConsultarGrupo = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelT4Grupos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT4Grupos.setText("Grupos");

        BtT4AddContatoGrupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4AddContatoGrupo.setText("Adicionar contato a um grupo");
        BtT4AddContatoGrupo.setActionCommand("");
        BtT4AddContatoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT4AddContatoGrupoActionPerformed(evt);
            }
        });

        BtT4EditUser.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4EditUser.setText("Meu usuário");
        BtT4EditUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT4EditUserActionPerformed(evt);
            }
        });

        BtT4Contato.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4Contato.setText("Novo contato");
        BtT4Contato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT4ContatoActionPerformed(evt);
            }
        });

        LabelT4Compromissos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT4Compromissos.setText("Compromissos");

        BtT4Compromissos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4Compromissos.setText("Novo compromisso");
        BtT4Compromissos.setToolTipText("");
        BtT4Compromissos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT4CompromissosActionPerformed(evt);
            }
        });

        LabelT4Contatos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT4Contatos.setText("Contatos");

        LabelT6Nome.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 52)); // NOI18N
        LabelT6Nome.setText("Nome");

        LabelT6Agenda.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 52)); // NOI18N
        LabelT6Agenda.setText("Agenda de");

        BtT4Atualizar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4Atualizar.setText("Atualizar");
        BtT4Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT4AtualizarActionPerformed(evt);
            }
        });

        BtT4NovoGrupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4NovoGrupo.setText("Novo grupo");
        BtT4NovoGrupo.setActionCommand("Novo Grupo");
        BtT4NovoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT4NovoGrupoActionPerformed(evt);
            }
        });

        TableT4Grupos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        TableT4Grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(TableT4Grupos);

        TableT4Contatos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        TableT4Contatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(TableT4Contatos);

        TableT4Compromissos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        TableT4Compromissos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Participantes", "Inicio", "Fim"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane7.setViewportView(TableT4Compromissos);

        BtT4ConsultarGrupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT4ConsultarGrupo.setText("Consultar Grupos");
        BtT4ConsultarGrupo.setActionCommand("");
        BtT4ConsultarGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT4ConsultarGrupoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(127, 127, 127)
                                .addComponent(LabelT4Contatos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LabelT4Grupos))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(LabelT6Agenda)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelT6Nome)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(264, 264, 264)
                                        .addComponent(BtT4EditUser))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtT4Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabelT4Compromissos)
                                .addGap(107, 107, 107)))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(BtT4Contato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtT4AddContatoGrupo)
                .addGap(165, 165, 165)
                .addComponent(BtT4Compromissos)
                .addGap(108, 108, 108))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(469, 469, 469)
                        .addComponent(BtT4ConsultarGrupo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(490, 490, 490)
                        .addComponent(BtT4NovoGrupo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtT4EditUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtT4Atualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelT6Nome)
                        .addComponent(LabelT6Agenda)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelT4Contatos)
                    .addComponent(LabelT4Compromissos)
                    .addComponent(LabelT4Grupos))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtT4Compromissos)
                    .addComponent(BtT4Contato)
                    .addComponent(BtT4AddContatoGrupo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtT4ConsultarGrupo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtT4NovoGrupo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtT4EditUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT4EditUserActionPerformed
        this.setVisible(false);
        this.t6.setVisible(true);
    }//GEN-LAST:event_BtT4EditUserActionPerformed

    private void BtT4ContatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT4ContatoActionPerformed
        this.setVisible(false);
        this.t2.setVisible(true);
    }//GEN-LAST:event_BtT4ContatoActionPerformed

    private void BtT4AddContatoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT4AddContatoGrupoActionPerformed
        this.setVisible(false);
        this.t5.setVisible(true);
    }//GEN-LAST:event_BtT4AddContatoGrupoActionPerformed

    private void BtT4CompromissosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT4CompromissosActionPerformed
        this.setVisible(false);
        this.t3.setVisible(true);
    }//GEN-LAST:event_BtT4CompromissosActionPerformed

    private void BtT4AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT4AtualizarActionPerformed
        AtualizarContatos();
        AtualizarGrupos();
    }//GEN-LAST:event_BtT4AtualizarActionPerformed

    private void BtT4NovoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT4NovoGrupoActionPerformed
        this.setVisible(false);
        this.t7.setVisible(true);
    }//GEN-LAST:event_BtT4NovoGrupoActionPerformed

    private void BtT4ConsultarGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT4ConsultarGrupoActionPerformed
        this.setVisible(false);
        this.t8.setVisible(true);
    }//GEN-LAST:event_BtT4ConsultarGrupoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TMain().setVisible(true);
            }
        });
    }
    
    void AtualizarContatos(){
        AgendaDAO contatoDAO = new AgendaDAO();
        List<Contato> contatos = new ArrayList<Contato>();
        contatos  = getContato();
        
        modelContatos.setRowCount(0);
        
        for (int i = 0; i < contatos.size(); i++)
        {
            modelContatos.insertRow(modelContatos.getRowCount(), new Object[]{String.valueOf(contatos.get(i).getId()), String.valueOf(contatos.get(i).getNome()), String.valueOf(contatos.get(i).getTelefone())});
        }
    }
    
    void AtualizarGrupos(){
        GrupoDAO grupoDAO = new GrupoDAO();
        List<Grupo> grupos = new ArrayList<Grupo>();
        grupos  = getGrupo();
        
        modelGrupos.setRowCount(0);
        
        for (int k = 0; k < grupos.size(); k = k+1)
        {
            modelGrupos.insertRow(modelGrupos.getRowCount(), new Object[]{String.valueOf(grupos.get(k).getId()), String.valueOf(grupos.get(k).getNome())});
        }
    }
    
    void setTelas(TInicial t1, TContato t2, TCompromisso t3, TGrupo t5, TUsuario t6,  TCriarGrupo t7, TVisualizarGrupos t8) {
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
        this.t5 = t5;
        this.t6 = t6;
        this.t7 = t7;
        this.t8 = t8;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtT4AddContatoGrupo;
    private javax.swing.JButton BtT4Atualizar;
    private javax.swing.JButton BtT4Compromissos;
    private javax.swing.JButton BtT4ConsultarGrupo;
    private javax.swing.JButton BtT4Contato;
    private javax.swing.JButton BtT4EditUser;
    private javax.swing.JButton BtT4NovoGrupo;
    private javax.swing.JLabel LabelT4Compromissos;
    private javax.swing.JLabel LabelT4Contatos;
    private javax.swing.JLabel LabelT4Grupos;
    private javax.swing.JLabel LabelT6Agenda;
    private javax.swing.JLabel LabelT6Nome;
    private javax.swing.JTable TableT4Compromissos;
    private javax.swing.JTable TableT4Contatos;
    private javax.swing.JTable TableT4Grupos;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
