/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import DAO.AgendaDAO;
import static DAO.AgendaDAO.getContato;
import DAO.CompromissoDAO;
import static DAO.CompromissoDAO.getCompromissos;
import static agenda.TVerCompromissos.bd;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author gabif
 */
public class TVerContatos extends javax.swing.JFrame {

    private TMain t4;
    private int cont = 0;
    public static  ArrayList<agenda.Contato> bd = new ArrayList<agenda.Contato>();
    
    public TVerContatos() {
        initComponents();
        
        bd = (ArrayList<Contato>) getContato();
        AttContatos();
        
        LabelT10IDN.setText(String.valueOf(this.bd.get(cont).getId()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextT10Telefone = new javax.swing.JTextField();
        TextT10DtNasc = new javax.swing.JTextField();
        TextT10Email = new javax.swing.JTextField();
        LabelT10Contato = new javax.swing.JLabel();
        BtT10Editar = new javax.swing.JButton();
        LabelT2DtNasc = new javax.swing.JLabel();
        LabelT2Nome = new javax.swing.JLabel();
        LabelT2Telefone = new javax.swing.JLabel();
        BtT10Salvar = new javax.swing.JButton();
        LabelT2Endereco = new javax.swing.JLabel();
        LabelT2Email = new javax.swing.JLabel();
        TextT10Nome = new javax.swing.JTextField();
        TextT10Endereco = new javax.swing.JTextField();
        BtT10Voltar = new javax.swing.JButton();
        BtT10Anterior = new javax.swing.JButton();
        BtT10Proximo = new javax.swing.JButton();
        BtT10Apagar = new javax.swing.JButton();
        LabelT10ID = new javax.swing.JLabel();
        LabelT10IDN = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TextT10Telefone.setEnabled(false);

        TextT10DtNasc.setEnabled(false);

        TextT10Email.setEnabled(false);

        LabelT10Contato.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 36)); // NOI18N
        LabelT10Contato.setText("Todos os Contatos");

        BtT10Editar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT10Editar.setText("Editar");
        BtT10Editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT10EditarActionPerformed(evt);
            }
        });

        LabelT2DtNasc.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2DtNasc.setText("Data de Nascimento");

        LabelT2Nome.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Nome.setText("Nome");

        LabelT2Telefone.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Telefone.setText("Telefone");

        BtT10Salvar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT10Salvar.setText("Salvar");
        BtT10Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT10SalvarActionPerformed(evt);
            }
        });

        LabelT2Endereco.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Endereco.setText("Endereco");

        LabelT2Email.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT2Email.setText("E-mail");

        TextT10Nome.setEnabled(false);
        TextT10Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextT10NomeActionPerformed(evt);
            }
        });

        TextT10Endereco.setEnabled(false);

        BtT10Voltar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT10Voltar.setText("Voltar");
        BtT10Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT10VoltarActionPerformed(evt);
            }
        });

        BtT10Anterior.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT10Anterior.setText("Anterior");
        BtT10Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT10AnteriorActionPerformed(evt);
            }
        });

        BtT10Proximo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT10Proximo.setText("Próximo");
        BtT10Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT10ProximoActionPerformed(evt);
            }
        });

        BtT10Apagar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT10Apagar.setText("Apagar");
        BtT10Apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT10ApagarActionPerformed(evt);
            }
        });

        LabelT10ID.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT10ID.setText("ID");

        LabelT10IDN.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT10IDN.setText("?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtT10Editar)
                        .addGap(18, 18, 18)
                        .addComponent(BtT10Apagar)
                        .addGap(480, 480, 480)
                        .addComponent(BtT10Salvar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(LabelT10ID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelT10IDN)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelT10Contato)
                        .addGap(146, 146, 146)
                        .addComponent(BtT10Voltar)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelT2DtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Email, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(BtT10Anterior)
                        .addGap(18, 18, 18)
                        .addComponent(BtT10Proximo))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(TextT10Email)
                        .addComponent(TextT10DtNasc)
                        .addComponent(TextT10Endereco)
                        .addComponent(TextT10Telefone)
                        .addComponent(TextT10Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelT10Contato)
                    .addComponent(BtT10Voltar)
                    .addComponent(LabelT10ID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelT10IDN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelT2DtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT10DtNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelT2Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT10Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelT2Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT10Telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelT2Email, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT10Email, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelT2Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT10Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(303, 303, 303)))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtT10Editar)
                    .addComponent(BtT10Salvar)
                    .addComponent(BtT10Proximo)
                    .addComponent(BtT10Anterior)
                    .addComponent(BtT10Apagar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtT10EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT10EditarActionPerformed
        EnableEdit();
    }//GEN-LAST:event_BtT10EditarActionPerformed

    private void BtT10SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT10SalvarActionPerformed
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        java.sql.Date data = null;
        try {
            data = new java.sql.Date(formato.parse(this.TextT10DtNasc.getText()).getTime());
        } catch (ParseException ex) {
            Logger.getLogger(TContato.class.getName()).log(Level.SEVERE, null, ex);
        }

        AgendaDAO agendaDao = new AgendaDAO();
        Contato c = new Contato();

        //c.setId();
        this.bd.get(cont).setNome(TextT10Nome.getText());
        this.bd.get(cont).setNascimento(data);
        this.bd.get(cont).setEndereco(TextT10Endereco.getText());
        this.bd.get(cont).setTelefone(TextT10Telefone.getText());
        this.bd.get(cont).setEmail(TextT10Email.getText());
        
        c.setId(Integer.parseInt(this.LabelT10IDN.getText()));
        c.setNome(this.TextT10Nome.getText());
        c.setNascimento(data);
        c.setEndereco(this.TextT10Endereco.getText());
        c.setTelefone(this.TextT10Telefone.getText());
        c.setEmail(this.TextT10Email.getText());

        AgendaDAO.Update(c);
        
        DisableEdit();
    }//GEN-LAST:event_BtT10SalvarActionPerformed

    private void TextT10NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextT10NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextT10NomeActionPerformed

    private void BtT10VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT10VoltarActionPerformed
        this.setVisible(false);
        this.t4.setVisible(true);
    }//GEN-LAST:event_BtT10VoltarActionPerformed

    private void BtT10AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT10AnteriorActionPerformed
        if (cont < 1) {
        cont = bd.size()-1;
        } else {
        cont--;
        }
        DisableEdit();
        AttContatos();
        LabelT10IDN.setText(String.valueOf(this.bd.get(cont).getId()));
    }//GEN-LAST:event_BtT10AnteriorActionPerformed

    private void BtT10ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT10ProximoActionPerformed
        if (cont > bd.size()-2){
        cont = 0;
        } else {
        cont++;
        }
        DisableEdit();
        AttContatos();
        LabelT10IDN.setText(String.valueOf(this.bd.get(cont).getId()));
    }//GEN-LAST:event_BtT10ProximoActionPerformed

    private void BtT10ApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT10ApagarActionPerformed
        String a = this.TextT10Nome.getText();
        int resposta = JOptionPane.showConfirmDialog( null,"Confirma a exclusão de "+a+" ?", "Exclusão de Compromisso",JOptionPane.YES_NO_OPTION);
        
        if(resposta == 0){
            AgendaDAO.Delete(this.bd.get(cont).getId());
        
            bd = (ArrayList<Contato>) getContato();
            AttContatos();
        }
    }//GEN-LAST:event_BtT10ApagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TVerContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TVerContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TVerContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TVerContatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TVerContatos().setVisible(true);
            }
        });
    }
    
    void setTelas (TMain t4){
        this.t4 = t4;
    }
    
    
    void AttContatos(){
        this.TextT10Nome.setText(this.bd.get(cont).getNome());
        this.TextT10DtNasc.setText(String.valueOf(this.bd.get(cont).getNascimento()));
        this.TextT10Endereco.setText(this.bd.get(cont).getEndereco());
        this.TextT10Telefone.setText(String.valueOf(this.bd.get(cont).getTelefone()));
        this.TextT10Email.setText(this.bd.get(cont).getEmail());
        
    }
    
    void EnableEdit(){
        this.TextT10Nome.setEnabled(true);
        this.TextT10DtNasc.setEnabled(true);
        this.TextT10Endereco.setEnabled(true);
        this.TextT10Telefone.setEnabled(true);
        this.TextT10Email.setEnabled(true);
    }
    
    void DisableEdit(){
        this.TextT10Nome.setEnabled(false);
        this.TextT10DtNasc.setEnabled(false);
        this.TextT10Endereco.setEnabled(false);
        this.TextT10Telefone.setEnabled(false);
        this.TextT10Email.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtT10Anterior;
    private javax.swing.JButton BtT10Apagar;
    private javax.swing.JButton BtT10Editar;
    private javax.swing.JButton BtT10Proximo;
    private javax.swing.JButton BtT10Salvar;
    private javax.swing.JButton BtT10Voltar;
    private javax.swing.JLabel LabelT10Contato;
    private javax.swing.JLabel LabelT10ID;
    private javax.swing.JLabel LabelT10IDN;
    private javax.swing.JLabel LabelT2DtNasc;
    private javax.swing.JLabel LabelT2Email;
    private javax.swing.JLabel LabelT2Endereco;
    private javax.swing.JLabel LabelT2Nome;
    private javax.swing.JLabel LabelT2Telefone;
    private javax.swing.JTextField TextT10DtNasc;
    private javax.swing.JTextField TextT10Email;
    private javax.swing.JTextField TextT10Endereco;
    private javax.swing.JTextField TextT10Nome;
    private javax.swing.JTextField TextT10Telefone;
    // End of variables declaration//GEN-END:variables
}
