/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import DAO.AgendaDAO;
import static DAO.AgendaDAO.getContato;
import DAO.GrupoContatoDAO;
import static DAO.GrupoContatoDAO.getContatoGrupo;
import DAO.GrupoDAO;
import static DAO.GrupoDAO.getGrupo;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class TVisualizarGrupos extends javax.swing.JFrame {
    
    private TInicial t1;
    private TContato t2;
    private TCompromisso t3;
    private TMain t4;
    private TGrupo t5;
    private TUsuario t6;
    private TCriarGrupo t7;
    
    DefaultTableModel modelGrupo;
    
    public TVisualizarGrupos() {
        initComponents();
        
        modelGrupo = (DefaultTableModel) TabT8Grupos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextT8IDGrupo = new javax.swing.JTextField();
        LabelT5Todos = new javax.swing.JLabel();
        BtT8Voltar = new javax.swing.JButton();
        BtT8AddContatoGrupo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabT8Grupos = new javax.swing.JTable();
        LabelT5Nome = new javax.swing.JLabel();
        LabelT5NovoGrupo = new javax.swing.JLabel();
        BtT8Pesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LabelT5Todos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 24)); // NOI18N
        LabelT5Todos.setText("Grupo");

        BtT8Voltar.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT8Voltar.setText("Voltar");
        BtT8Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT8VoltarActionPerformed(evt);
            }
        });

        BtT8AddContatoGrupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        BtT8AddContatoGrupo.setText("Adicionar contato a um grupo");
        BtT8AddContatoGrupo.setActionCommand("");
        BtT8AddContatoGrupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT8AddContatoGrupoActionPerformed(evt);
            }
        });

        TabT8Grupos.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 14)); // NOI18N
        TabT8Grupos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Telefone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabT8Grupos);

        LabelT5Nome.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 18)); // NOI18N
        LabelT5Nome.setText("Insira ID do grupo a ser consultado:");

        LabelT5NovoGrupo.setFont(new java.awt.Font("PMingLiU-ExtB", 0, 36)); // NOI18N
        LabelT5NovoGrupo.setText("Consultar Grupo");

        BtT8Pesquisar.setText("Pesquisar");
        BtT8Pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtT8PesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtT8AddContatoGrupo)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelT5Nome)
                                .addGap(18, 18, 18)
                                .addComponent(TextT8IDGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtT8Pesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(LabelT5Todos)))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelT5NovoGrupo)
                        .addGap(255, 255, 255)
                        .addComponent(BtT8Voltar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelT5NovoGrupo)
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelT5Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TextT8IDGrupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BtT8Pesquisar))
                        .addGap(26, 26, 26)
                        .addComponent(BtT8AddContatoGrupo))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtT8Voltar)
                        .addGap(40, 40, 40)
                        .addComponent(LabelT5Todos, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(166, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtT8VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT8VoltarActionPerformed
        this.t4.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtT8VoltarActionPerformed

    private void BtT8AddContatoGrupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT8AddContatoGrupoActionPerformed
        this.setVisible(false);
        this.t5.setVisible(true);
    }//GEN-LAST:event_BtT8AddContatoGrupoActionPerformed

    private void BtT8PesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtT8PesquisarActionPerformed
        
        GrupoContato gp = new GrupoContato();
        gp.setIdGrupo(Integer.parseInt(TextT8IDGrupo.getText()));
        AgendaDAO contatoDAO = new AgendaDAO();
        List<Contato> contatos = new ArrayList<Contato>();
        contatos  = getContato();
        
        GrupoContatoDAO grupocDAO = new GrupoContatoDAO();
        List<GrupoContato> grupocontato = new ArrayList<GrupoContato>();
        grupocontato = getContatoGrupo();
        
        modelGrupo.setRowCount(0);
        
        for (int i = 0; i < grupocontato.size(); i++)
        {
            modelGrupo.insertRow(modelGrupo.getRowCount(), new Object[]{String.valueOf(grupocontato.get(i).getNomeContato()), String.valueOf(contatos.get(i).getTelefone())});
        }
    }//GEN-LAST:event_BtT8PesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TVisualizarGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TVisualizarGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TVisualizarGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TVisualizarGrupos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TVisualizarGrupos().setVisible(true);
            }
        });
    }
    
    void setTelas(TInicial t1, TContato t2, TCompromisso t3, TMain t4, TGrupo t5, TUsuario t6,  TCriarGrupo t7) {
        this.t1 = t1;
        this.t2 = t2;
        this.t3 = t3;
        this.t4 = t4;
        this.t5 = t5;
        this.t6 = t6;
        this.t7 = t7;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtT8AddContatoGrupo;
    private javax.swing.JButton BtT8Pesquisar;
    private javax.swing.JButton BtT8Voltar;
    private javax.swing.JLabel LabelT5Nome;
    private javax.swing.JLabel LabelT5NovoGrupo;
    private javax.swing.JLabel LabelT5Todos;
    private javax.swing.JTable TabT8Grupos;
    private javax.swing.JTextField TextT8IDGrupo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
